# System configuration
ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = ../arduino-makefile
AVR_TOOLS_DIR = /usr

# Arduino config
BOARD_TAG        = mega2560
ARDUINO_PORT     = /dev/ttyACM0
ARDUINO_LIBS     = 
MONITOR_BAUDRATE = 9600

include ../arduino-makefile/arduino-mk/Arduino.mk
